import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

// Tailwind → Font Weight:
// - font-thin → 100
// - font-extralight → 200
// - font-light → 300
// - font-normal → 400
// - font-medium → 500
// - font-semibold → 600
// - font-bold → 700
// - font-extrabold → 800
// - font-black → 900

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>{children}</body>
    </html>
  );
}
